apiVersion: apps/v1
kind: Deployment
metadata:
 name: nginx-deploy
 labels:
   app: nginx-web
spec:
  replicas: 4
  selector:
   matchLabels:
     app: nginx-web
  template:
   metadata:
     labels:
       app: nginx-web
   spec:
     containers:
     - name: nginx
       image: nginx
       ports:
       - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
 name: nginx-svc
spec:
 selector:
  app: nginx-web
 ports:
 - port: 9000
   targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-nodeport
spec:
  type: NodePort
  selector:
    app: nginx-web
  ports:
    - port: 9000
      targetPort: 80
      nodePort: 31000
